## template: jinja
#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
write_files:
- path: /etc/sysctl.d/10-ip-forwarding.conf
  content: |
    net.ipv4.ip_forward=1
- path: /etc/iptables/rules.v4
  content: |
    # Generated by iptables-save v1.8.4 on Tue Aug 24 19:16:37 2021
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    COMMIT
    # Completed on Tue Aug 24 19:16:37 2021
    # Generated by iptables-save v1.8.4 on Tue Aug 24 19:16:37 2021
    *nat
    :PREROUTING ACCEPT [0:0]
    :INPUT ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    :POSTROUTING ACCEPT [0:0]
    -A POSTROUTING -o bond0 -j MASQUERADE
    COMMIT
    # Completed on Tue Aug 24 19:16:37 2021
- path: /etc/iptables/rules.v6
  content: |
    # Generated by ip6tables-save v1.8.4 on Tue Aug 24 19:16:37 2021
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    COMMIT
- path: /etc/network/interfaces
  append: true
  content: |

    auto bond0.${metal_vlan_id}
    iface bond0.${metal_vlan_id} inet static
        pre-up sleep 5
        address ${address}
        netmask ${netmask}
        vlan-raw-device bond0
- path: /etc/dnsmasq.d/openshift.config
  append: true
  content: |
    bind-interfaces
    interface=bond0.${metal_vlan_id}
    dhcp-range=${host_dhcp_start},${host_dhcp_end},${lease_time}
packages:
  - iptables
  - iptables-services
  - dnsmasq
runcmd:
- sysctl -p /etc/sysctl.d/10-ip-forwarding.conf
- systemctl restart networking
- systemctl restart dnsmasq